#!/usr/bin/env python3
"""Sync Collegium Magorum from contributors.json + GitHub API into README and wiki."""
from __future__ import annotations

import json
import re
import shutil
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "contributors.json"
DOCS_CONFIG = ROOT / "docs" / "contributors.json"
MARKER_START = "<!-- collegium:start"
MARKER_END = "<!-- collegium:end -->"

TARGETS = [
    ROOT / "README.md",
    ROOT / "wiki" / "Home.md",
]


def load_config() -> dict:
    with CONFIG_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def fetch_contributors(repo: str) -> list[dict]:
    url = f"https://api.github.com/repos/{repo}/contributors?per_page=100"
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "vox-gothica-collegium-sync",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def merge_roll(config: dict, api_contributors: list[dict]) -> list[dict]:
    by_login = {c["login"].lower(): c for c in api_contributors}
    seen: set[str] = set()
    out: list[dict] = []

    for pinned in config.get("pinned", []):
        login = (pinned.get("github") or "").lower() or None
        if login:
            seen.add(login)
        api = by_login.get(login) if login else None
        out.append(
            {
                "display": pinned.get("display")
                or (api and api["login"])
                or pinned.get("github")
                or "Unknown",
                "title": pinned.get("title") or config.get("default_title", "Contributor"),
                "url": (api and api.get("html_url")) or pinned.get("url"),
            }
        )

    default_title = config.get("default_title", "Contributor")
    for contributor in api_contributors:
        login = contributor["login"].lower()
        if login in seen:
            continue
        seen.add(login)
        out.append(
            {
                "display": contributor["login"],
                "title": default_title,
                "url": contributor.get("html_url"),
            }
        )

    return out


def markdown_table(entries: list[dict]) -> str:
    lines = [
        f"{MARKER_START} — auto-generated by sync-collegium.py; edit contributors.json for titles -->",
        "",
        "| | |",
        "|---|---|",
    ]
    for entry in entries:
        name = entry["display"]
        if entry.get("url"):
            name = f"[**{entry['display']}**]({entry['url']})"
        else:
            name = f"**{entry['display']}**"
        lines.append(f"| {name} | {entry['title']} |")
    lines.append(MARKER_END)
    return "\n".join(lines)


def wiki_table(entries: list[dict]) -> str:
    lines = [
        f"{MARKER_START} — auto-generated by sync-collegium.py; edit contributors.json for titles -->",
        "",
        "| Name | Title |",
        "|------|-------|",
    ]
    for entry in entries:
        name = entry["display"]
        if entry.get("url"):
            name = f"[{entry['display']}]({entry['url']})"
        lines.append(f"| {name} | {entry['title']} |")
    lines.append(MARKER_END)
    return "\n".join(lines)


def patch_file(path: Path, block: str) -> bool:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf"{re.escape(MARKER_START)}.*?{re.escape(MARKER_END)}",
        re.DOTALL,
    )
    if not pattern.search(text):
        print(f"skip: no collegium markers in {path}", file=sys.stderr)
        return False
    updated = pattern.sub(block, text)
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8")
    print(f"updated: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    config = load_config()
    repo = config.get("repository", "adeptusprogus/vox-gothica")
    try:
        api_contributors = fetch_contributors(repo)
    except urllib.error.URLError as exc:
        print(f"github api failed: {exc}", file=sys.stderr)
        return 1

    entries = merge_roll(config, api_contributors)
    shutil.copy2(CONFIG_PATH, DOCS_CONFIG)
    print(f"copied: {DOCS_CONFIG.relative_to(ROOT)}")

    changed = False
    readme_block = markdown_table(entries)
    wiki_block = wiki_table(entries)

    if patch_file(ROOT / "README.md", readme_block):
        changed = True
    if patch_file(ROOT / "wiki" / "Home.md", wiki_block):
        changed = True

    if not changed:
        print("collegium: already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
