"""gothica sigillum — seal a CANTICUM into a standalone executable (M5+)."""
from __future__ import annotations

import subprocess
import sys
import textwrap
from pathlib import Path


def _pkg_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _boot_source(principium_rel: str, app_root_rel: str) -> str:
    return textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """Sealed canticle entry — generated by gothica sigillum."""
        import os
        import sys
        from pathlib import Path

        PRINCIPIUM = {principium_rel!r}
        APP_ROOT = {app_root_rel!r}


        def _bundle_root() -> Path:
            if getattr(sys, "frozen", False):
                return Path(sys._MEIPASS)
            return Path(__file__).resolve().parent


        def main() -> int:
            os.environ.setdefault("GOTHICA_CENSURA", "N")
            bundle = _bundle_root()
            app_root = bundle / APP_ROOT
            scroll = bundle / PRINCIPIUM
            if not scroll.is_file():
                print(f"⚙ sealed scroll missing: {{scroll}}", file=sys.stderr)
                return 2
            from gothica.parser import parse_source
            from gothica.interpres import Interpres
            from gothica.heresiae import Heresis

            text = scroll.read_text(encoding="utf-8")
            prog = parse_source(text, str(scroll))
            if prog.mode != "CANTICUM":
                print(f"⚙ sigillum requires a CANTICUM (got {{prog.mode}})", file=sys.stderr)
                return 2
            interp = Interpres(root_dir=str(app_root.resolve()))
            try:
                interp.run_program(prog)
            except Heresis as h:
                print(f"⚙ HERESIS [{{h.genus}}] {{h.nuntius}}", file=sys.stderr)
                return 1
            return 0


        if __name__ == "__main__":
            raise SystemExit(main())
        '''
    )


def seal(
    principium: str | Path,
    *,
    nomine: str | None = None,
    fenestra: bool = False,
    out_dir: str | Path | None = None,
    work_dir: str | Path | None = None,
) -> Path:
    """Bundle principium.vg + sibling scrolls into a PyInstaller one-file binary."""
    scroll = Path(principium).resolve()
    if not scroll.is_file():
        raise FileNotFoundError(f"no scroll at '{scroll}'")

    pkg = _pkg_root()
    app_root = scroll.parent
    try:
        rel_scroll = scroll.relative_to(pkg).as_posix()
        rel_app = app_root.relative_to(pkg).as_posix()
    except ValueError:
        rel_scroll = scroll.name
        rel_app = "."

    name = nomine or app_root.name.replace("-", "_")
    name = "".join(c if c.isalnum() or c == "_" else "_" for c in name)

    out = Path(out_dir or pkg / "dist").resolve()
    work = Path(work_dir or pkg / "build" / "sigillum").resolve()
    work.mkdir(parents=True, exist_ok=True)
    out.mkdir(parents=True, exist_ok=True)

    boot = work / "sigillum_boot.py"
    boot.write_text(_boot_source(rel_scroll, rel_app), encoding="utf-8")

    add_data: list[str] = []
    for fp in sorted(app_root.rglob("*.vg")):
        dest = fp.relative_to(pkg).parent.as_posix() or "."
        add_data.extend(["--add-data", f"{fp}:{dest}"])
    lit = app_root / "litania.toml"
    if lit.is_file():
        add_data.extend(["--add-data", f"{lit}:{rel_app}"])

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",
        "--name", name,
        "--distpath", str(out),
        "--workpath", str(work / "pyi"),
        "--specpath", str(work / "pyi"),
        "--collect-submodules", "gothica",
        *add_data,
    ]
    if fenestra:
        cmd.append("--windowed")
    cmd.append(str(boot))

    subprocess.run(cmd, check=True, cwd=str(pkg))
    binary = out / (f"{name}.exe" if sys.platform == "win32" else name)
    if not binary.is_file():
        matches = sorted(out.glob(f"{name}*"))
        if not matches:
            raise RuntimeError(f"sigillum finished but no binary in {out}")
        binary = matches[0]
    return binary
